config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: "home#index"

  # Routes for approved tasks
    get 'task_applications/approve', to: "task_applications#approve_task_application", as: 'approved_task'
    #get '/tasks/approved_tasks', to: "tasks#approved_tasks", as: 'approved_tasks'
    get 'task_applications/pending_approval', to: "task_applications#pending_approval", as: 'pending_approval'
    get 'declined', to: 'task_applications#decline', as: 'decline_task_application'

  # Routes for favourited tasks page
    get 'favourites', to: "tasks#favourites", as: 'favourites'
  
  # Routes for viewing of all tasks, favouriting them and commenting them
  resources :tasks do
    member do
      post 'toggle_favorite', to: "tasks#toggle_favorite"
    end
    resources :comments
  end

  # User profiles page routes
   get 'profile', to: 'user#current_user_profile', as: 'user_profile'
   get 'user/:id', to: 'user#profile', as: 'profile'
  
   # Dashboard route
   get 'dashboard', to: 'user#dashboard', as: 'dashboard'

  resources :comments
  resources :task_applications
  resources :completed_tasks
  resources :categories
  resources :cities

  # Devise routes used for user authentication
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task

  # data santization
  before_save :remove_whitespace
  
  validates :message, presence: :true

  private

  def remove_whitespace
    self.message = self.message.strip
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_task, only: %i[update destroy create]
  before_action :set_comment, only: %i[update destroy]
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :current_user, only: %i[create destroy]

  def create
    @comment = @task.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
          format.html { redirect_to @task }
          format.json { render :show, status: :created, 
      location: @task }
      else
          format.html { redirect_to @task, alert: 'post not 
          commented' }
          format.json { render json: @task.errors, status: 
          :unprocessable_entity }
      end
    end
  end

	def destroy
		@comment = @task.comments.find(params[:id])
		@comment.destroy
		redirect_to task_path(@task)
	end

  private

  def comment_params
    params.require(:comment).permit(:message, :task_id)
  end

  def set_task
    @task = Task.find(params[:task_id])
  end

  def set_comment
    @comment = @task.comments.find(params[:id])
  end

end

app/views/comments/_comment.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-1 align-middle">
      <!-- show user picture if they have one -->
      <% if comment.user.picture.attached? %>
        <%= image_tag comment.user.picture, width: "65px", class:"img-thumbnail" %>
      <% else %>
          <%= image_tag "anonymous.png", width: "65px", class:"img-thumbnail" %>
      <% end %>
    </div>

    <div class="col-lg-11">
      <p>
      <strong>User: </strong><%= comment.user.first_name %> <%= comment.user.surname %>:</p>
      <p><%= comment.message %></p>

      <p><small><i class="fa fa-clock"></i> Posted 
        <%= time_ago_in_words(comment.created_at) %> ago</small></p>

      <% if comment.user == current_user || current_user.admin %>
        <%= link_to 'Delete', [comment.task, comment],
        method: :delete, class: "bn btn-danger", data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@task, @task.comments.build{}]) do |f| %>
<!--
collection.build(attributes = {}, …) Returns one or more new objects of the collection type that have been instantiated with attributes and linked to this object through a foreign key, but have not yet been saved. Note: This only works if an associated object already exists, not if it‘s nil!
-->
<div class="field">

  <div class="field">
    <div class="control">
      <%= f.input :message, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
<%= f.button :submit, 'Leave a reply', class: "button btn-primary my-3" %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>