config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: "home#index"

  # Routes for approved tasks
    get 'task_applications/approve', to: "task_applications#approve_task_application", as: 'approved_task'
    #get '/tasks/approved_tasks', to: "tasks#approved_tasks", as: 'approved_tasks'
    get 'task_applications/pending_approval', to: "task_applications#pending_approval", as: 'pending_approval'
    get 'declined', to: 'task_applications#decline', as: 'decline_task_application'

  # Routes for favourited tasks page
    get 'favourites', to: "tasks#favourites", as: 'favourites'
  
  # Routes for viewing of all tasks, favouriting them and commenting them
  resources :tasks do
    member do
      post 'toggle_favorite', to: "tasks#toggle_favorite"
    end
    resources :comments
  end

  # User profiles page routes
   get 'profile', to: 'user#current_user_profile', as: 'user_profile'
   get 'user/:id', to: 'user#profile', as: 'profile'
  
   # Dashboard route
   get 'dashboard', to: 'user#dashboard', as: 'dashboard'

  resources :comments
  resources :task_applications
  resources :completed_tasks
  resources :categories
  resources :cities

  # Devise routes used for user authentication
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/task.rb
class Task < ApplicationRecord
    # Show 3 tasks per page (from Kaminari gem)
    paginates_per 3

    # BELOW EXTENSIONS ARE NOT USED IN THIS VERSION OF OUTSOURCE
    # Extend Class Sortable so that tasks can be searched
    # include Sortable::InstanceMethods
    # extend Sortable::ClassMethods 

    # From rubygem
    acts_as_favoritable

    belongs_to :user
    belongs_to :category
    has_many :comments, dependent: :destroy 
    has_many :task_applications, dependent: :destroy 

    # Validations
    validates :title, presence: true
    validates :user, presence: true
    validates :description, presence: true
    validates :category, presence: true

    # Data santization
    before_save :remove_whitespace

    private

    # Check category of self (for category filter)
    def self.by_category(category_id)
        where(category: category_id)
    end

    def remove_whitespace
        self.title = self.title.strip
        self.description = self.description.strip
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :setup_form, only: [:new, :edit]
  before_action :set_task, only: %i[ show edit update destroy toggle_favorite ]
  before_action :current_user, only: %i[create destroy ]

  # GET /tasks or /tasks.json 
  def index
    @categories = Category.all

    # Only show tasks that are not sourced and are not posted by the user
    # Filter by Category
    if !params[:category_id].blank?
      @tasks = Task.by_category(params[:category_id])
      .where.not(:user_id => current_user.id).where(sourced: [nil, false ]).page params[:page]
    else
      @tasks = Task.where.not(:user_id => current_user.id).where(sourced: [nil, false ]).page params[:page]
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @task}
    end
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  # If user is creator OR Admin
  def edit
    authorize @task
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  # If user is creator OR Admin
  def update
    authorize @task
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  # If user is creator OR Admin
  def destroy
    authorize @task
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # Toggle favourite on / favourite off 
  def toggle_favorite
    current_user.favorited?(@task) ? current_user.unfavorite(@task) : current_user.favorite(@task)
  end

  # List tasks user has favourited
  def favourites
    @favourite_tasks = current_user.favorited_by_type('Task')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def setup_form
      @categories = Category.all
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :price, :user_id, :category_id, :comment, :task_date, :sourced, :remote_work)
    end

end

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <% @task.errors.full_messages.each do |message|%>\
  <h3><%= message %> </h3>
  <%end%>
<%end%>

<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.collection_select :category_id, Category.order(:title), :id, :title, required: true %>
    <br><br>
    <%= f.input :remote_work, :label => "This work can be compeleted remotely", as: :boolean %>
    <%= f.date_field :task_date, min: Date.today %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary my-3" %>
  </div>
<% end %>

app/views/tasks/_like_button.html.erb
<div class="like-icon mx-3 <%= 'red' if current_user.favorited?(task) %>" data-id="<%= task.id %>">
  <i class="fas fa-heart fa-2x"></i>
</div>

app/views/tasks/_task.html.erb
<div class="py-4">
  <div class="card">
    <div class="card-header" >
      <td><%= task.category.title %></td>
    </div>

    <div class="card-body">
      <div class="row">
        <%= link_to toggle_favorite_task_path(task), remote: true, method: :post do %>
          <%= render 'tasks/like_button', task: task %>
        <% end %>
        <h2><%= task.title %></h2>
      </div>

    <div class="card-text">
      <%= task.description %>
    </div>
    
    <div class="row">
      <div class="col-lg-9">
        <div class="card-text">
          <p class="btn btn-success">
            $<%= task.price %>
          </p>
        </div>

        <div class="card-text">
          <% if task.remote_work %>
            <p class="badge badge-warning">Can be completed remotely</p>
          <% end %>
        </div>

        <% if task.task_date %>
          <p>
          <strong>Task to be completed on:</strong>
          <%= task.task_date.strftime("%d-%m-%Y") %>
          </p>
        <% else %>
          <p>This task has a flexible completion date.</p></p>
        <% end %>

        <div class="comment-count">
          <span class="tag is-rounded"><%= task.comments.count %> comments</span>
        </div>

        <div class="favourite-count">
          <span class="tag is-rounded">
          <% if task.favoritable_score.values.empty? %>
            0 favourites
          <% else %>
            <%= task.favoritable_score.values[0] %>
            favourites</span>
          <%end%>
        </div>
        <br>

        <div class="links-container">
        <!-- Display links depending on user who is logged in -->
          <% if current_user %>
            <% if current_user.has_applied?(task.id) %>
                <%= link_to 'Applied', task_applications_path, class: "btn btn-primary" %>
            <% elsif task.user == current_user || current_user.admin  %>
                <%= link_to 'Edit', edit_task_path(task), class: "btn btn-info" %>
                <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
            <% else %>
                  <%= link_to 'Apply', new_task_application_path(task_id: task.id, user_id: current_user), class: "btn btn-primary" %>
            <% end %>
            <%= link_to 'Show', task, class: "btn btn-info" %>
          <% end %>
        </div>
      </div>

    <div class='col-lg-3 col-md-6 col-sm-12 mt-5'>
      <% if task.user.picture.attached? %>
        <%= image_tag task.user.picture, width: "100px", class:"img-thumbnail " %>
      <% else %>
        <%= image_tag "anonymous.png", width: "100px", class:"img-thumbnail rounded" %>
      <% end %>
      <p><i class="fa fa-user"></i> <%= task.user.first_name %> <%= task.user.surname %></p>
    </div>
	</div>
</div>

app/views/tasks/approved_task.html.erb
<div class="card container mt-5" style="height: 400px">
	<div class="container p-5">
		<div class="row">
			<div class="col-lg-8">
			<h2>You've approved the task:</h2>
			</div>
		</div>
	</div>
</div>

app/views/tasks/edit.html.erb
<div class="card container mt-5 w-75 p-5">
    <h1>Editing Task</h1>

    <%= render 'form', task: @task %>
    <%= link_to 'Show', @task %> 
    <%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/favourites.html.erb
<div class="page container mt-4
">
	<% if @favourite_tasks.any? %>
		<h1 class="text-white text-center">Your favourited tasks</h1>
		<% @favourite_tasks.each do |task| %>
			<%= render 'task', task: task %>
		<% end %>
	<% else %>
		<div class="container">
		<h1 class="text-white text-center mt-4">You've got no tasks favourited!</h1>
				
		<div class='mx-auto'>
				<%= image_tag "happy.png", width: "350px", alt: "Happy lady", class: "rounded mx-auto d-block"  %>
		</div>

		<div class="card container p-3">
			<h2 class="text-center">Where would you like to go?</h2>
			<div class="row d-flex justify-content-between w-75 mx-auto">
				<%= link_to 'Dashboard', dashboard_path, class: "btn btn-primary col-lg-3" %>
				<%= link_to 'Home', '/', class: "btn btn-primary col-lg-3 mx-2" %>
				<%= link_to 'Tasks', tasks_path, class: "btn btn-primary col-lg-3 mx-2" %>
			</div>
		</div>
	<% end %>
</div>

app/views/tasks/index.html.erb
<div class="page container">
  <h1 class="text-white text-center m-3">Tasks near you</h1>

	<div class="my-4">
		<%= paginate @tasks %>
	</div>

	<!-- CATEGORY FILTER --> 
	<%= bootstrap_form_tag url: '/tasks', method: 'get' do |f| %>
		<%= f.collection_select :category_id, Category.all, :id, :title %>
		<%= f.submit "Filter" %>
	<% end %>

	<% @tasks.each do |task| %>
		<div class="py-4">
			<%= render 'task', task: task %>
		</div>
	<% end %>

	<div class="mt-4">
		<%= paginate @tasks %>
	</div>
</div>

app/views/tasks/new.html.erb
<div class="card container mt-5 w-75 p-5">
  <h1 class="">New Task</h1>
  <%= render 'form', task: @task %>
	<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="card container p-5 mt-5">
  <div class="row">
    <div class="task col-lg-6 col-md-6 col-sm-12">
      <p>
        <h1><%= @task.title %></h1>
      </p>

      <p>
        <strong>About the task:</strong><br>
        <%= @task.description %>
      </p>

      <p>
        <strong>Price:</strong><br>
        $<%= @task.price %>
      </p>

      <p>
        <strong>Category:</strong>
        <%= @task.category.title %>
      </p>

      <% if @task.task_date %>
      <p>
        <strong>Task to be completed on:</strong>
        <%= @task.task_date.strftime("%d-%m-%Y") %>
      </p>
      <% else %>
        <p>This task has a flexible completion date.</p></p>
      <% end %>
    
      <p>
        <strong>User:</strong>
        <%= @task.user.first_name %> <%= @task.user.surname %>
      </p>

      <p>
        <i class="fa fa-clock"></i> Posted 
          <%= time_ago_in_words(@task.created_at) %> ago
      </p>
    </div>

    <div class='col-lg-4 col-md-6 col-sm-12'>
      <% if @task.user.picture.attached? %>
        <%= image_tag @task.user.picture, width: "200px", class:"" %>
      <% else %>
          <%= image_tag "anonymous.png", width: "200px", class:"" %>
      <% end %>
      
      <p class="align-middle">
        <strong>User:</strong>
        <%= @task.user.first_name %> <%= @task.user.surname %>
      </p> 
    </div>
  </div>

    <div class="container w-100">
      <h2 class="subtitle is-5"><strong><%= @task.comments.count %></strong> Comments</h2>
      <%= render @task.comments %>
      <div class="comment-form">
        <hr />
        <h3 class="subtitle is-3">Leave a reply</h3>
        <%= render 'comments/form' %>
      </div>
    </div>

  <% if @task.user == current_user %>
    <%= link_to 'Edit', edit_task_path(@task), class: "btn btn-info" %>
  <% end %>
    <%= link_to 'Back', tasks_path, class: "btn btn-primary" %>
</div>

app/views/tasks/toggle_favorite.js.erb
var taskId = '<%= @task.id%>'
function toggleLikeButton(taskId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${taskId}']`)
  likeButton.classList.toggle('red');
}
toggleLikeButton(taskId);