config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: "home#index"

  # Routes for approved tasks
    get 'task_applications/approve', to: "task_applications#approve_task_application", as: 'approved_task'
    #get '/tasks/approved_tasks', to: "tasks#approved_tasks", as: 'approved_tasks'
    get 'task_applications/pending_approval', to: "task_applications#pending_approval", as: 'pending_approval'
    get 'declined', to: 'task_applications#decline', as: 'decline_task_application'

  # Routes for favourited tasks page
    get 'favourites', to: "tasks#favourites", as: 'favourites'
  
  # Routes for viewing of all tasks, favouriting them and commenting them
  resources :tasks do
    member do
      post 'toggle_favorite', to: "tasks#toggle_favorite"
    end
    resources :comments
  end

  # User profiles page routes
   get 'profile', to: 'user#current_user_profile', as: 'user_profile'
   get 'user/:id', to: 'user#profile', as: 'profile'
  
   # Dashboard route
   get 'dashboard', to: 'user#dashboard', as: 'dashboard'

  resources :comments
  resources :task_applications
  resources :completed_tasks
  resources :categories
  resources :cities

  # Devise routes used for user authentication
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/task_application.rb
class TaskApplication < ApplicationRecord
  belongs_to :user
  belongs_to :task

  # data santization
  before_save :remove_whitespace

  # data validation
  validates :message, presence: true

  private
  def remove_whitespace
    self.message = self.message.strip
  end
end

app/controllers/task_applications_controller.rb
class TaskApplicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task_application, only: %i[ show edit update destroy ]

  # GET /applications or /applications.json 
  def index
     # Applications that the  current user has posted
    @task_applications = TaskApplication.where(:user_id => current_user.id )
  end

  # GET /applications/1 or /applications/1.json
  def show
  end

  # Retrieve tasks posted by this user that
  # 1. haven't been declined 
  # 2. Haven't been sourced yet. 
  def pending_approval
    @task_applications = TaskApplication.joins(:task).where(tasks: { user_id: current_user, sourced: nil}, :approved => nil)

  end

  # GET /applications/new
  def new
    # new task with task ID from task being applied to
    @task_application = TaskApplication.new
    @task = Task.find(params[:task_id])
  end

  # GET /applications/1/edit
  def edit
  end


  # POST /applications or /applications.json
  def create
    # Checks if this task is already applied for
    @task_application = TaskApplication.find_by_user_id_and_task_id(params[:task_application][:user_id], params[:task_application][:task_id])
    if !@task_application.nil?
      redirect_to @task_application, alert: "You've already applied for this task."
    else
      @task_application = TaskApplication.new(task_application_params)
      respond_to do |format|
        if @task_application.save
          format.html { redirect_to task_applications_path, notice: "Application was successfully created." }
          format.json { render :show, status: :created, location: @task_application }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @task_application.errors, status: :unprocessable_entity }
        end
      end
    end
  end


  # PATCH/PUT /applications/1 or /applications/1.json
  def update
    respond_to do |format|
      if @task_application.update(task_application_params)
        format.html { redirect_to @task_application, notice: "Application was successfully updated." }
        format.json { render :show, status: :ok, location: @task_application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1 or /applications/1.json
  def destroy
    @task_application.destroy
    respond_to do |format|
      format.html { redirect_to pending_approval_path, notice: "Application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def approve_task_application
    # find task that is being approved
    application = TaskApplication.find(params[:task_application_id])
    approved_task = Task.find(application.task.id)
    # set task to sourced
    approved_task.sourced = true
    # set application to approved
    application.approved = true
    respond_to do |format|
      if application.save && approved_task.save
        format.html { redirect_to profile_path(application.user), notice: "Task was successfully approved!" }
        format.json { render :show, status: :created, location: approved_task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: approved_task.errors, status: :unprocessable_entity }
      end
    end
  end

  def decline
    @task_application = TaskApplication.find(params[:task_application_id])
    @task_application.approved = false
    if @task_application.save
      respond_to do |format|
        format.html { redirect_to pending_approval_path, notice: "Application was successfully declined" }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_application
      @task_application = TaskApplication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_application_params
      params.require(:task_application).permit(:message, :user_id, :task_id)
    end
end

app/views/task_applications/_form.html.erb
<%= simple_form_for(@task_application) do |f| %>
  <%= f.hidden_field :user_id, :value => params[:user_id] %>
  <%= f.hidden_field :task_id, :value => params[:task_id] %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :message, :as => :text, input_html: {rows: 6, cols: 5} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/task_applications/edit.html.erb
<div class="card container mt-5 w-75 p-5">
	<h1>Editing Application</h1>

	<%= render 'form', application: @task_application %>

	<%= link_to 'Show', @task_application %>
	<%= link_to 'Back', task_applications_path %>
</div>

app/views/task_applications/index.html.erb
<div class="container mt-5">
  <h1 class="text-white text-center">Your Applications</h1>
  <% @task_applications.each do |task_application| %>
    <div class="card container p-4 m-4">
      <h2><%= task_application.task.title %></h2>

      <!-- APPLICATION STATUS -->
      <div class="w-25">
      <!-- if neither approved or declined -->
        <% if task_application.approved.nil? && task_application.task.sourced.nil? %>
          <p class="btn btn-sm btn-warning">Pending approval</p>
        <!-- if approved -->
        <% elsif task_application.approved %>
          <p class="btn btn-sm btn-success">Approved</p>
        <!-- if task poster has declined application or has approved another application for this task -->
        <% elsif !task_application.approved || (task_application.approved.nil? && !task_application.task.sourced.nil?) %>
          <p class="btn btn-sm btn-danger">Declined</p>
        <% end %>
      </div>
      
      <p><strong>Your message: </strong><%= task_application.message %>
      <br><br>

      <i class="fa fa-user"></i> 
      <%= task_application.task.user.first_name %> <%= task_application.task.user.surname %>
      <br>
      <i class="fa fa-clock"></i> 
      Application sent <%= time_ago_in_words(task_application.created_at)%></p>

      <div class="links-container">
        <%= link_to 'View task', task_path(task_application.task), class: "btn btn-info" %>
        <%= link_to 'Destroy', task_application, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
      <br>
  
      <%= mail_to(task_application.task.user.email) do %>
        <strong class="btn btn-success w-100">Email User</strong>
      <% end %>
    </div>
  <% end %>
</div>

app/views/task_applications/new.html.erb
<div class="card container mt-5 w-75 p-5">
	<div class="row">
		<div class="col-lg-11 col-md-10">
			<h2>Describe why you'd be fit to:</h2>
			<br>
			<h3><%= @task.title %></h3>

			<% if @task.task_date %>
				<p><%= @task.task_date.strftime("%Y %m %d") %></p>
			<% else %>
				<p>This task has flexible completion date</p>
			<% end %>

			<br>
			<%= render 'form', application: @task_application %>
			<br>

			<%= link_to 'Back', tasks_path %>
		</div>

		<div class="col-lg-1 col-md-1 bg-dark">
			
		</div>
	</div>
</div>

app/views/task_applications/pending_approval.html.erb
<div class="page container mt-4">

	<% if @task_applications.any? %>
		<h1 class="text-white">Please review the following applications:</h1>
		<% @task_applications.each do |task_application| %>
			<div class="card">
				<div class="card-header" >
					<td><strong>Your task: </strong><%= task_application.task.title %></td>
				</div>
				
				<div class="card-body">
					<div class="h2">
						<%= task_application.user.first_name %> <%= task_application.user.surname %>
					</div>
					<p><%= task_application.message %></p>
					<br>

					<div class="row mx-2">
						<%= link_to 'Approve', approved_task_path(task_application_id: task_application.id), class: "btn btn-primary mx-1" %>
						<%= link_to 'Decline', decline_task_application_path(task_application_id: task_application.id), data: { confirm: 'Are you sure?' }, class: "btn btn-danger mx-1" %>
					</div>
				</div>
				<br>
			</div>
		<% end %>
		
	<% else %>

		<!-- User has no applications to review -->
		<div class="container">
			<h1 class="text-white text-center mt-4">You've got no applications to review!</h1>		
			<div class='mx-auto'>
				<%= image_tag "happy.png", width: "350px", alt: "Happy lady", class: "rounded mx-auto d-block"  %>
			</div>

			<div class="card container p-3">
				<h2 class="text-center">Where would you like to go?</h2>
				<div class="row d-flex justify-content-between w-75 mx-auto">
					<%= link_to 'Dashboard', dashboard_path, class: "btn btn-primary col-lg-3" %>
					<%= link_to 'Home', '/', class: "btn btn-primary col-lg-3 mx-2" %>
					<%= link_to 'Tasks', tasks_path, class: "btn btn-primary col-lg-3 mx-2" %>
				</div>
			</div>
		</div>
	<% end %>
<br>
</div>

app/views/task_applications/show.html.erb
<p>
  <strong>Message:</strong>
  <%= @task_application.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @task_application.user_id %>
</p>

<p>
  <strong>Task:</strong>
  <%= @task_application.task_id %>
</p>

<%= link_to 'Edit', edit_task_application_path(@task_application) %> |
<%= link_to 'Back', task_applications_path %>