config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: "home#index"

  # Routes for approved tasks
    get 'task_applications/approve', to: "task_applications#approve_task_application", as: 'approved_task'
    #get '/tasks/approved_tasks', to: "tasks#approved_tasks", as: 'approved_tasks'
    get 'task_applications/pending_approval', to: "task_applications#pending_approval", as: 'pending_approval'
    get 'declined', to: 'task_applications#decline', as: 'decline_task_application'

  # Routes for favourited tasks page
    get 'favourites', to: "tasks#favourites", as: 'favourites'
  
  # Routes for viewing of all tasks, favouriting them and commenting them
  resources :tasks do
    member do
      post 'toggle_favorite', to: "tasks#toggle_favorite"
    end
    resources :comments
  end

  # User profiles page routes
   get 'profile', to: 'user#current_user_profile', as: 'user_profile'
   get 'user/:id', to: 'user#profile', as: 'profile'
  
   # Dashboard route
   get 'dashboard', to: 'user#dashboard', as: 'dashboard'

  resources :comments
  resources :task_applications
  resources :completed_tasks
  resources :categories
  resources :cities

  # Devise routes used for user authentication
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
end

app/models/user.rb
class User < ApplicationRecord
  # From rubygem
  acts_as_favoritor

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks # tasks the user has posted
  has_many :comments, dependent: :destroy
  has_one_attached :picture 
  has_many :task_applications, dependent: :destroy 

  # data santisation
  before_save :remove_whitespace

  # input validation
  validates :first_name, presence: true
  validates :surname, presence: true

  # returns total number of application user needs to review
  def total_applications_to_be_reviewed
    count = @task_applications = TaskApplication.joins(:task).where(tasks: { user_id: self.id, sourced: nil}, :approved => nil).to_a.count
    return count
  end

  # Checks if user has already sent an application for a task
  def has_applied?(task_id)
    if !task_applications.find_by_task_id(task_id).nil?
      true
    end
  end
  
  # returns total number of tasks user has completed 
  def total_completed
      count = TaskApplication.where( user_id: self.id, approved: true ).to_a.count
      return count
  end

  private 
  
  def remove_whitespace
    self.first_name = self.first_name.strip
    self.surname = self.surname.strip
    # devise automatically sanitises user email
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    # def create
    #     params[:user][:city] = City.find(params[:user][:city_id])
    #     super
    # end

    # show user with this ID
    def profile
        @user = User.find(params[:id])
    end
    
    # dashboard page
    def dashboard
        # show latest 3 tasks that user hasn't posted and haven't been sourced
        @latest_tasks = Task.where.not(:user_id => current_user.id).where(sourced: [nil, false ]).last(3)
        # show tasks that user has posted that haven't been sourced
        @active_tasks = Task.where(:user_id => current_user.id, sourced: [nil, false])
    end
    
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # Update redirect to after profile update 
  def after_update_path_for(resource)
    dashboard_path
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/dashboard.html.erb
<div class="dash-body container d-flex flex-column">
	<div class="card container p-5 mt-5">
	<div class="row">
		<!-- Display 'Admin' badge if user is admin -->
		<div class="col-lg-9 col-md-7">
			<h1 class="d-inline">Welcome back, <%= current_user.first_name%>!</h1>
			<% if current_user.admin? %>
				<span class="badge badge-danger">Admin view</span>
			<% end %>
			<hr>

			<!-- Display number of applications pending review -->
			<div class="row">
				<%= link_to(pending_approval_path) do %>
					<button class="btn btn-success m-1">Needs review <span class="badge badge-light">
						<%= current_user.total_applications_to_be_reviewed.to_s %>
					</span></button>
				<% end %>
			</div>

			<!-- Alert user they need to give more information about themselves -->
			<% if current_user.about_me.nil? || current_user.about_me == "" %>
				<p class="badge badge-warning">We are missing some information about you, please complete your profile:</p>
				<br><%= link_to 'Edit profile', edit_user_registration_url, class: "btn btn-primary m-1" %>
			<% end %>
		</div>

		<div class="col-lg-2 m-4 col-md-1 p-2">
			<% if current_user.picture.attached? %>
				<%= image_tag current_user.picture, width: "100px", class:"" %>
			<% else %>
				<%= image_tag "anonymous.png", width: "100px", class:"" %>
				<%= link_to 'Add picture', edit_user_registration_url, class: "btn btn-primary btn-sm mx-auto mt-3" %>
			<% end %>
			</div>
		</div>
	</div>

<div class="row">
	<div class="col-lg-7">
		<div class="card container p-3 mt-3">
			<h2>Create a new task!</h2>
				<%= link_to 'New task', new_task_path, class: "btn btn-success m-1" %>
		</div>

		<h2 class="text-white text-center mt-3">Check out some tasks near you:</h2>
			
		<% @latest_tasks.each do |task| %>
			<div class="card container mt-3 p-4">
				<div class="row">
				<div class="col-lg-8">
					<h5><%= link_to task.title, task_path(task) %></h5>

					<small><p><%= task.category.title %></p></small>
			
					<small><p><i class="fa fa-clock"></i> Posted 
					<%= time_ago_in_words(task.created_at) %> ago
					</p></small>

					<%= link_to 'Apply', new_task_application_path(task_id: task.id, user_id: current_user), class: "btn btn-primary" %>
					<%= link_to 'Show', task, class: "btn btn-info" %> 
					</div>

					<div class="col-lg-3">
						<% if task.user.picture.attached? %>
							<%= image_tag task.user.picture, width: "100px", class:"" %>
						<% else %>
							<%= image_tag "anonymous.png", width: "100px", style: ""%>
						<% end %>
						<p class="text-center"><%= task.user.first_name %> <%= task.user.surname %></p>
					</div>
					</div>
				</div>
			<% end %>
		</div>

		<div class="col-lg-5">
			<div class="card container p-3 mt-3">
			<h2>Your account:</h2>
				<%= link_to 'Edit profile', edit_user_registration_url, class: "btn btn-info m-1" %>
				<%= link_to 'Favourites', favourites_path, class: "btn btn-info m-1" %>
				<%= link_to 'Applications', task_applications_path, class: "btn btn-info m-1" %>
			</div>

				<div class="card container p-3 mt-3">
				<% if @active_tasks.any?%>
					<h2>Active tasks:</h2>
					<% @active_tasks.each do |task| %>
					<div class="card">
						<div class="card-body">
							<h5 class="card-title"><%= link_to task.title, task_path(task) %></h5>
							<small><p class="card-text"><i class="fa fa-clock"></i> Posted 
							<%= time_ago_in_words(task.created_at) %> ago
							</p></small><br>
							<%= link_to 'Show', task, class: "btn btn-primary" %>
							<%= link_to 'Edit', edit_task_path(task), class: "btn btn-primary" %>
							<%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary"%>
						</div>
					</div>
					<% end %>
				<% else %>
					<h2>You have no active tasks!</h2>
					<%= link_to 'New task', new_task_path, class: "btn btn-success m-1" %>
				<% end %>
						
				</div>

	</div>
</div>

app/views/user/profile.html.erb
<div class="card container mt-5">
	<div class="row p-5">

		<div class="col-lg-4">
			<% if @user.picture.attached? %>
        <%= image_tag @user.picture, width: "200px", class:"" %>
      <% else %>
          <%= image_tag "anonymous.png", width: "200px", class:"" %>
      <% end %>
      
      <p class="align-middle">
        <strong>User:</strong>
        <%= @user.first_name %> <%= @user.surname %>
      </p> 
		</div>

		<div class="col-lg-8">
			<h1><%= @user.first_name%> <%= @user.surname%></h1>
		
			<% if @user.about_me.nil? || @user.about_me == ""  %>
				<p>This user is shy, they haven't got any information about themselves on their profile!</p>
			<% else %>
				<p><%= @user.about_me %></p>
			<% end %>

			<p class="badge badge-info">They have completed a total of <%= @user.total_completed.to_s %> tasks</p>

			<%= mail_to(@user.email) do %>
          		<strong class="btn btn-success w-100">Email User</strong>
        	<% end %>
		</div>
	
	</div>
</div>